begin;
create extension if not exists pgtap with schema extensions;
select plan(17);
select has_table('public','group_chat_messages','chat messages exist');
select has_column('public','world_members','joined_after_seq','membership cutoff exists');
select ok(to_regclass('private.group_chat_authors') is not null,'author identity mapping is private');
select ok(to_regclass('private.group_chat_reads') is not null,'read cursor is private');
select ok(to_regclass('private.group_chat_requests') is not null,'deduplication is private');
select ok(to_regprocedure('public.send_group_chat_message(uuid,uuid,text)') is not null,'restricted send signature');
select ok(to_regprocedure('public.send_group_chat_message(uuid,uuid,text,jsonb)') is null,'no client profile argument');
select ok((select relrowsecurity from pg_class where oid='public.group_chat_messages'::regclass),'public messages use RLS');
select ok(not has_table_privilege('anon','public.group_chat_messages','SELECT'),'anonymous has no table access');
select ok(not has_table_privilege('authenticated','public.group_chat_messages','INSERT'),'direct insert denied');
select ok(not has_table_privilege('authenticated','public.group_chat_messages','UPDATE'),'direct update denied');
select ok(not has_table_privilege('authenticated','private.group_chat_authors','SELECT'),'Auth mapping inaccessible');
select ok(not has_table_privilege('authenticated','private.group_chat_reads','SELECT'),'other read cursors inaccessible');
select ok(not has_table_privilege('authenticated','private.group_chat_requests','SELECT'),'requests inaccessible');
select ok(not has_function_privilege('anon','public.get_group_chat_context(uuid)','EXECUTE'),'anonymous RPC denied');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000009999',true);
select throws_ok($$select public.get_group_chat_context('90000000-0000-0000-0000-000000009999')$$,'42501',null,'nonmember context denied');
select is((select count(*) from public.group_chat_messages),0::bigint,'nonmember direct visibility empty');
reset role;
select * from finish();
rollback;
